### ISSUE TITLE
createRestaurant {name} {address} {UIN} {MRP} {initialCapital}

### ISSUE THREAD

**Issue by MaxuelRenner** [The-A-Team-PTG/RestaurantManager#4]
– създава ресторант с
определено име, адрес, ЕИК, материално отговорно лице и начален капитал, например
createRestaurant PizzaCodexia CityPalaceCenter 205427773 IvanYonkov 1000

printRestaurantInfo {name} – дава инфо за ресторант по име – всичките му свойства.

**Comment by dimitar-13** [comment]
The class Restaurant is commited on the branch  Restaurant with all  of the {name,address,UIN,MRP,initialCapital]
